# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_uploadedcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedCSV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
