# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_scrapedcsv_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scrapedcsv',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 15, 31, 9, 833294, tzinfo=utc)),
        ),
    ]
