# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20170410_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled')], max_length=64),
        ),
        migrations.AlterField(
            model_name='scrapedcsv',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 16, 12, 30, 93430, tzinfo=utc)),
        ),
    ]
