# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20170410_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scrapedcsv',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 16, 35, 32, 222438, tzinfo=utc)),
        ),
    ]
